// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	badger "github.com/dgraph-io/badger/v3"
	domain "github.com/eleven-am/graft/internal/domain"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	ports "github.com/eleven-am/graft/internal/ports"

	time "time"
)

// MockRaftNode is an autogenerated mock type for the RaftNode type
type MockRaftNode struct {
	mock.Mock
}

type MockRaftNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRaftNode) EXPECT() *MockRaftNode_Expecter {
	return &MockRaftNode_Expecter{mock: &_m.Mock}
}

// Apply provides a mock function with given fields: cmd, timeout
func (_m *MockRaftNode) Apply(cmd domain.Command, timeout time.Duration) (*domain.CommandResult, error) {
	ret := _m.Called(cmd, timeout)

	if len(ret) == 0 {
		panic("no return value specified for Apply")
	}

	var r0 *domain.CommandResult
	var r1 error
	if rf, ok := ret.Get(0).(func(domain.Command, time.Duration) (*domain.CommandResult, error)); ok {
		return rf(cmd, timeout)
	}
	if rf, ok := ret.Get(0).(func(domain.Command, time.Duration) *domain.CommandResult); ok {
		r0 = rf(cmd, timeout)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommandResult)
		}
	}

	if rf, ok := ret.Get(1).(func(domain.Command, time.Duration) error); ok {
		r1 = rf(cmd, timeout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRaftNode_Apply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Apply'
type MockRaftNode_Apply_Call struct {
	*mock.Call
}

// Apply is a helper method to define mock.On call
//   - cmd domain.Command
//   - timeout time.Duration
func (_e *MockRaftNode_Expecter) Apply(cmd interface{}, timeout interface{}) *MockRaftNode_Apply_Call {
	return &MockRaftNode_Apply_Call{Call: _e.mock.On("Apply", cmd, timeout)}
}

func (_c *MockRaftNode_Apply_Call) Run(run func(cmd domain.Command, timeout time.Duration)) *MockRaftNode_Apply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Command), args[1].(time.Duration))
	})
	return _c
}

func (_c *MockRaftNode_Apply_Call) Return(_a0 *domain.CommandResult, _a1 error) *MockRaftNode_Apply_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRaftNode_Apply_Call) RunAndReturn(run func(domain.Command, time.Duration) (*domain.CommandResult, error)) *MockRaftNode_Apply_Call {
	_c.Call.Return(run)
	return _c
}

// Broadcast provides a mock function with given fields: msg
func (_m *MockRaftNode) Broadcast(msg []byte) {
	_m.Called(msg)
}

// MockRaftNode_Broadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Broadcast'
type MockRaftNode_Broadcast_Call struct {
	*mock.Call
}

// Broadcast is a helper method to define mock.On call
//   - msg []byte
func (_e *MockRaftNode_Expecter) Broadcast(msg interface{}) *MockRaftNode_Broadcast_Call {
	return &MockRaftNode_Broadcast_Call{Call: _e.mock.On("Broadcast", msg)}
}

func (_c *MockRaftNode_Broadcast_Call) Run(run func(msg []byte)) *MockRaftNode_Broadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockRaftNode_Broadcast_Call) Return() *MockRaftNode_Broadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRaftNode_Broadcast_Call) RunAndReturn(run func([]byte)) *MockRaftNode_Broadcast_Call {
	_c.Run(run)
	return _c
}

// GetClusterInfo provides a mock function with no fields
func (_m *MockRaftNode) GetClusterInfo() ports.ClusterInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClusterInfo")
	}

	var r0 ports.ClusterInfo
	if rf, ok := ret.Get(0).(func() ports.ClusterInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.ClusterInfo)
	}

	return r0
}

// MockRaftNode_GetClusterInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterInfo'
type MockRaftNode_GetClusterInfo_Call struct {
	*mock.Call
}

// GetClusterInfo is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) GetClusterInfo() *MockRaftNode_GetClusterInfo_Call {
	return &MockRaftNode_GetClusterInfo_Call{Call: _e.mock.On("GetClusterInfo")}
}

func (_c *MockRaftNode_GetClusterInfo_Call) Run(run func()) *MockRaftNode_GetClusterInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_GetClusterInfo_Call) Return(_a0 ports.ClusterInfo) *MockRaftNode_GetClusterInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_GetClusterInfo_Call) RunAndReturn(run func() ports.ClusterInfo) *MockRaftNode_GetClusterInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealth provides a mock function with no fields
func (_m *MockRaftNode) GetHealth() ports.HealthStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 ports.HealthStatus
	if rf, ok := ret.Get(0).(func() ports.HealthStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.HealthStatus)
	}

	return r0
}

// MockRaftNode_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type MockRaftNode_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) GetHealth() *MockRaftNode_GetHealth_Call {
	return &MockRaftNode_GetHealth_Call{Call: _e.mock.On("GetHealth")}
}

func (_c *MockRaftNode_GetHealth_Call) Run(run func()) *MockRaftNode_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_GetHealth_Call) Return(_a0 ports.HealthStatus) *MockRaftNode_GetHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_GetHealth_Call) RunAndReturn(run func() ports.HealthStatus) *MockRaftNode_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetLeadershipInfo provides a mock function with no fields
func (_m *MockRaftNode) GetLeadershipInfo() ports.RaftLeadershipInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLeadershipInfo")
	}

	var r0 ports.RaftLeadershipInfo
	if rf, ok := ret.Get(0).(func() ports.RaftLeadershipInfo); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.RaftLeadershipInfo)
	}

	return r0
}

// MockRaftNode_GetLeadershipInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeadershipInfo'
type MockRaftNode_GetLeadershipInfo_Call struct {
	*mock.Call
}

// GetLeadershipInfo is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) GetLeadershipInfo() *MockRaftNode_GetLeadershipInfo_Call {
	return &MockRaftNode_GetLeadershipInfo_Call{Call: _e.mock.On("GetLeadershipInfo")}
}

func (_c *MockRaftNode_GetLeadershipInfo_Call) Run(run func()) *MockRaftNode_GetLeadershipInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_GetLeadershipInfo_Call) Return(_a0 ports.RaftLeadershipInfo) *MockRaftNode_GetLeadershipInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_GetLeadershipInfo_Call) RunAndReturn(run func() ports.RaftLeadershipInfo) *MockRaftNode_GetLeadershipInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetrics provides a mock function with no fields
func (_m *MockRaftNode) GetMetrics() ports.RaftMetrics {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetrics")
	}

	var r0 ports.RaftMetrics
	if rf, ok := ret.Get(0).(func() ports.RaftMetrics); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.RaftMetrics)
	}

	return r0
}

// MockRaftNode_GetMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetrics'
type MockRaftNode_GetMetrics_Call struct {
	*mock.Call
}

// GetMetrics is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) GetMetrics() *MockRaftNode_GetMetrics_Call {
	return &MockRaftNode_GetMetrics_Call{Call: _e.mock.On("GetMetrics")}
}

func (_c *MockRaftNode_GetMetrics_Call) Run(run func()) *MockRaftNode_GetMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_GetMetrics_Call) Return(_a0 ports.RaftMetrics) *MockRaftNode_GetMetrics_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_GetMetrics_Call) RunAndReturn(run func() ports.RaftMetrics) *MockRaftNode_GetMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// GetRaftStatus provides a mock function with no fields
func (_m *MockRaftNode) GetRaftStatus() ports.RaftStatus {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRaftStatus")
	}

	var r0 ports.RaftStatus
	if rf, ok := ret.Get(0).(func() ports.RaftStatus); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(ports.RaftStatus)
	}

	return r0
}

// MockRaftNode_GetRaftStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRaftStatus'
type MockRaftNode_GetRaftStatus_Call struct {
	*mock.Call
}

// GetRaftStatus is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) GetRaftStatus() *MockRaftNode_GetRaftStatus_Call {
	return &MockRaftNode_GetRaftStatus_Call{Call: _e.mock.On("GetRaftStatus")}
}

func (_c *MockRaftNode_GetRaftStatus_Call) Run(run func()) *MockRaftNode_GetRaftStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_GetRaftStatus_Call) Return(_a0 ports.RaftStatus) *MockRaftNode_GetRaftStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_GetRaftStatus_Call) RunAndReturn(run func() ports.RaftStatus) *MockRaftNode_GetRaftStatus_Call {
	_c.Call.Return(run)
	return _c
}

// IsLeader provides a mock function with no fields
func (_m *MockRaftNode) IsLeader() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsLeader")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockRaftNode_IsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsLeader'
type MockRaftNode_IsLeader_Call struct {
	*mock.Call
}

// IsLeader is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) IsLeader() *MockRaftNode_IsLeader_Call {
	return &MockRaftNode_IsLeader_Call{Call: _e.mock.On("IsLeader")}
}

func (_c *MockRaftNode_IsLeader_Call) Run(run func()) *MockRaftNode_IsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_IsLeader_Call) Return(_a0 bool) *MockRaftNode_IsLeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_IsLeader_Call) RunAndReturn(run func() bool) *MockRaftNode_IsLeader_Call {
	_c.Call.Return(run)
	return _c
}

// LeaderAddr provides a mock function with no fields
func (_m *MockRaftNode) LeaderAddr() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LeaderAddr")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockRaftNode_LeaderAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaderAddr'
type MockRaftNode_LeaderAddr_Call struct {
	*mock.Call
}

// LeaderAddr is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) LeaderAddr() *MockRaftNode_LeaderAddr_Call {
	return &MockRaftNode_LeaderAddr_Call{Call: _e.mock.On("LeaderAddr")}
}

func (_c *MockRaftNode_LeaderAddr_Call) Run(run func()) *MockRaftNode_LeaderAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_LeaderAddr_Call) Return(_a0 string) *MockRaftNode_LeaderAddr_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_LeaderAddr_Call) RunAndReturn(run func() string) *MockRaftNode_LeaderAddr_Call {
	_c.Call.Return(run)
	return _c
}

// OnBroadcast provides a mock function with given fields: fn
func (_m *MockRaftNode) OnBroadcast(fn func(string, []byte)) {
	_m.Called(fn)
}

// MockRaftNode_OnBroadcast_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnBroadcast'
type MockRaftNode_OnBroadcast_Call struct {
	*mock.Call
}

// OnBroadcast is a helper method to define mock.On call
//   - fn func(string , []byte)
func (_e *MockRaftNode_Expecter) OnBroadcast(fn interface{}) *MockRaftNode_OnBroadcast_Call {
	return &MockRaftNode_OnBroadcast_Call{Call: _e.mock.On("OnBroadcast", fn)}
}

func (_c *MockRaftNode_OnBroadcast_Call) Run(run func(fn func(string, []byte))) *MockRaftNode_OnBroadcast_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(string, []byte)))
	})
	return _c
}

func (_c *MockRaftNode_OnBroadcast_Call) Return() *MockRaftNode_OnBroadcast_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRaftNode_OnBroadcast_Call) RunAndReturn(run func(func(string, []byte))) *MockRaftNode_OnBroadcast_Call {
	_c.Run(run)
	return _c
}

// RegisterService provides a mock function with given fields: fn
func (_m *MockRaftNode) RegisterService(fn func(grpc.ServiceRegistrar)) {
	_m.Called(fn)
}

// MockRaftNode_RegisterService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterService'
type MockRaftNode_RegisterService_Call struct {
	*mock.Call
}

// RegisterService is a helper method to define mock.On call
//   - fn func(grpc.ServiceRegistrar)
func (_e *MockRaftNode_Expecter) RegisterService(fn interface{}) *MockRaftNode_RegisterService_Call {
	return &MockRaftNode_RegisterService_Call{Call: _e.mock.On("RegisterService", fn)}
}

func (_c *MockRaftNode_RegisterService_Call) Run(run func(fn func(grpc.ServiceRegistrar))) *MockRaftNode_RegisterService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(func(grpc.ServiceRegistrar)))
	})
	return _c
}

func (_c *MockRaftNode_RegisterService_Call) Return() *MockRaftNode_RegisterService_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockRaftNode_RegisterService_Call) RunAndReturn(run func(func(grpc.ServiceRegistrar))) *MockRaftNode_RegisterService_Call {
	_c.Run(run)
	return _c
}

// StateDB provides a mock function with no fields
func (_m *MockRaftNode) StateDB() *badger.DB {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StateDB")
	}

	var r0 *badger.DB
	if rf, ok := ret.Get(0).(func() *badger.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*badger.DB)
		}
	}

	return r0
}

// MockRaftNode_StateDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StateDB'
type MockRaftNode_StateDB_Call struct {
	*mock.Call
}

// StateDB is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) StateDB() *MockRaftNode_StateDB_Call {
	return &MockRaftNode_StateDB_Call{Call: _e.mock.On("StateDB")}
}

func (_c *MockRaftNode_StateDB_Call) Run(run func()) *MockRaftNode_StateDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_StateDB_Call) Return(_a0 *badger.DB) *MockRaftNode_StateDB_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_StateDB_Call) RunAndReturn(run func() *badger.DB) *MockRaftNode_StateDB_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *MockRaftNode) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRaftNode_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type MockRaftNode_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) Stop() *MockRaftNode_Stop_Call {
	return &MockRaftNode_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *MockRaftNode_Stop_Call) Run(run func()) *MockRaftNode_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_Stop_Call) Return(_a0 error) *MockRaftNode_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_Stop_Call) RunAndReturn(run func() error) *MockRaftNode_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// TransferLeadership provides a mock function with no fields
func (_m *MockRaftNode) TransferLeadership() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TransferLeadership")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRaftNode_TransferLeadership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferLeadership'
type MockRaftNode_TransferLeadership_Call struct {
	*mock.Call
}

// TransferLeadership is a helper method to define mock.On call
func (_e *MockRaftNode_Expecter) TransferLeadership() *MockRaftNode_TransferLeadership_Call {
	return &MockRaftNode_TransferLeadership_Call{Call: _e.mock.On("TransferLeadership")}
}

func (_c *MockRaftNode_TransferLeadership_Call) Run(run func()) *MockRaftNode_TransferLeadership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRaftNode_TransferLeadership_Call) Return(_a0 error) *MockRaftNode_TransferLeadership_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_TransferLeadership_Call) RunAndReturn(run func() error) *MockRaftNode_TransferLeadership_Call {
	_c.Call.Return(run)
	return _c
}

// TransferLeadershipTo provides a mock function with given fields: serverID
func (_m *MockRaftNode) TransferLeadershipTo(serverID string) error {
	ret := _m.Called(serverID)

	if len(ret) == 0 {
		panic("no return value specified for TransferLeadershipTo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRaftNode_TransferLeadershipTo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferLeadershipTo'
type MockRaftNode_TransferLeadershipTo_Call struct {
	*mock.Call
}

// TransferLeadershipTo is a helper method to define mock.On call
//   - serverID string
func (_e *MockRaftNode_Expecter) TransferLeadershipTo(serverID interface{}) *MockRaftNode_TransferLeadershipTo_Call {
	return &MockRaftNode_TransferLeadershipTo_Call{Call: _e.mock.On("TransferLeadershipTo", serverID)}
}

func (_c *MockRaftNode_TransferLeadershipTo_Call) Run(run func(serverID string)) *MockRaftNode_TransferLeadershipTo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRaftNode_TransferLeadershipTo_Call) Return(_a0 error) *MockRaftNode_TransferLeadershipTo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRaftNode_TransferLeadershipTo_Call) RunAndReturn(run func(string) error) *MockRaftNode_TransferLeadershipTo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRaftNode creates a new instance of MockRaftNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRaftNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRaftNode {
	mock := &MockRaftNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
