// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/eleven-am/graft/internal/domain"
	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	ports "github.com/eleven-am/graft/internal/ports"
)

// MockTransportPort is an autogenerated mock type for the TransportPort type
type MockTransportPort struct {
	mock.Mock
}

type MockTransportPort_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransportPort) EXPECT() *MockTransportPort_Expecter {
	return &MockTransportPort_Expecter{mock: &_m.Mock}
}

// GetLeaderInfo provides a mock function with given fields: ctx, peerAddr
func (_m *MockTransportPort) GetLeaderInfo(ctx context.Context, peerAddr string) (string, string, error) {
	ret := _m.Called(ctx, peerAddr)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderInfo")
	}

	var r0 string
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, string, error)); ok {
		return rf(ctx, peerAddr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, peerAddr)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = rf(ctx, peerAddr)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, peerAddr)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransportPort_GetLeaderInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderInfo'
type MockTransportPort_GetLeaderInfo_Call struct {
	*mock.Call
}

// GetLeaderInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - peerAddr string
func (_e *MockTransportPort_Expecter) GetLeaderInfo(ctx interface{}, peerAddr interface{}) *MockTransportPort_GetLeaderInfo_Call {
	return &MockTransportPort_GetLeaderInfo_Call{Call: _e.mock.On("GetLeaderInfo", ctx, peerAddr)}
}

func (_c *MockTransportPort_GetLeaderInfo_Call) Run(run func(ctx context.Context, peerAddr string)) *MockTransportPort_GetLeaderInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTransportPort_GetLeaderInfo_Call) Return(leaderID string, leaderAddr string, err error) *MockTransportPort_GetLeaderInfo_Call {
	_c.Call.Return(leaderID, leaderAddr, err)
	return _c
}

func (_c *MockTransportPort_GetLeaderInfo_Call) RunAndReturn(run func(context.Context, string) (string, string, error)) *MockTransportPort_GetLeaderInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterEngine provides a mock function with given fields: engine
func (_m *MockTransportPort) RegisterEngine(engine ports.EnginePort) {
	_m.Called(engine)
}

// MockTransportPort_RegisterEngine_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterEngine'
type MockTransportPort_RegisterEngine_Call struct {
	*mock.Call
}

// RegisterEngine is a helper method to define mock.On call
//   - engine ports.EnginePort
func (_e *MockTransportPort_Expecter) RegisterEngine(engine interface{}) *MockTransportPort_RegisterEngine_Call {
	return &MockTransportPort_RegisterEngine_Call{Call: _e.mock.On("RegisterEngine", engine)}
}

func (_c *MockTransportPort_RegisterEngine_Call) Run(run func(engine ports.EnginePort)) *MockTransportPort_RegisterEngine_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ports.EnginePort))
	})
	return _c
}

func (_c *MockTransportPort_RegisterEngine_Call) Return() *MockTransportPort_RegisterEngine_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransportPort_RegisterEngine_Call) RunAndReturn(run func(ports.EnginePort)) *MockTransportPort_RegisterEngine_Call {
	_c.Run(run)
	return _c
}

// RegisterRaft provides a mock function with given fields: raft
func (_m *MockTransportPort) RegisterRaft(raft ports.RaftNode) {
	_m.Called(raft)
}

// MockTransportPort_RegisterRaft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterRaft'
type MockTransportPort_RegisterRaft_Call struct {
	*mock.Call
}

// RegisterRaft is a helper method to define mock.On call
//   - raft ports.RaftNode
func (_e *MockTransportPort_Expecter) RegisterRaft(raft interface{}) *MockTransportPort_RegisterRaft_Call {
	return &MockTransportPort_RegisterRaft_Call{Call: _e.mock.On("RegisterRaft", raft)}
}

func (_c *MockTransportPort_RegisterRaft_Call) Run(run func(raft ports.RaftNode)) *MockTransportPort_RegisterRaft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(ports.RaftNode))
	})
	return _c
}

func (_c *MockTransportPort_RegisterRaft_Call) Return() *MockTransportPort_RegisterRaft_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransportPort_RegisterRaft_Call) RunAndReturn(run func(ports.RaftNode)) *MockTransportPort_RegisterRaft_Call {
	_c.Run(run)
	return _c
}

// RegisterWithServer provides a mock function with given fields: server
func (_m *MockTransportPort) RegisterWithServer(server grpc.ServiceRegistrar) {
	_m.Called(server)
}

// MockTransportPort_RegisterWithServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWithServer'
type MockTransportPort_RegisterWithServer_Call struct {
	*mock.Call
}

// RegisterWithServer is a helper method to define mock.On call
//   - server grpc.ServiceRegistrar
func (_e *MockTransportPort_Expecter) RegisterWithServer(server interface{}) *MockTransportPort_RegisterWithServer_Call {
	return &MockTransportPort_RegisterWithServer_Call{Call: _e.mock.On("RegisterWithServer", server)}
}

func (_c *MockTransportPort_RegisterWithServer_Call) Run(run func(server grpc.ServiceRegistrar)) *MockTransportPort_RegisterWithServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(grpc.ServiceRegistrar))
	})
	return _c
}

func (_c *MockTransportPort_RegisterWithServer_Call) Return() *MockTransportPort_RegisterWithServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockTransportPort_RegisterWithServer_Call) RunAndReturn(run func(grpc.ServiceRegistrar)) *MockTransportPort_RegisterWithServer_Call {
	_c.Run(run)
	return _c
}

// RequestAddVoter provides a mock function with given fields: ctx, leaderAddr, nodeID, nodeAddr
func (_m *MockTransportPort) RequestAddVoter(ctx context.Context, leaderAddr string, nodeID string, nodeAddr string) error {
	ret := _m.Called(ctx, leaderAddr, nodeID, nodeAddr)

	if len(ret) == 0 {
		panic("no return value specified for RequestAddVoter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, leaderAddr, nodeID, nodeAddr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransportPort_RequestAddVoter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequestAddVoter'
type MockTransportPort_RequestAddVoter_Call struct {
	*mock.Call
}

// RequestAddVoter is a helper method to define mock.On call
//   - ctx context.Context
//   - leaderAddr string
//   - nodeID string
//   - nodeAddr string
func (_e *MockTransportPort_Expecter) RequestAddVoter(ctx interface{}, leaderAddr interface{}, nodeID interface{}, nodeAddr interface{}) *MockTransportPort_RequestAddVoter_Call {
	return &MockTransportPort_RequestAddVoter_Call{Call: _e.mock.On("RequestAddVoter", ctx, leaderAddr, nodeID, nodeAddr)}
}

func (_c *MockTransportPort_RequestAddVoter_Call) Run(run func(ctx context.Context, leaderAddr string, nodeID string, nodeAddr string)) *MockTransportPort_RequestAddVoter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockTransportPort_RequestAddVoter_Call) Return(_a0 error) *MockTransportPort_RequestAddVoter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransportPort_RequestAddVoter_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockTransportPort_RequestAddVoter_Call {
	_c.Call.Return(run)
	return _c
}

// SendApplyCommand provides a mock function with given fields: ctx, nodeAddr, cmd
func (_m *MockTransportPort) SendApplyCommand(ctx context.Context, nodeAddr string, cmd *domain.Command) (*domain.CommandResult, string, error) {
	ret := _m.Called(ctx, nodeAddr, cmd)

	if len(ret) == 0 {
		panic("no return value specified for SendApplyCommand")
	}

	var r0 *domain.CommandResult
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Command) (*domain.CommandResult, string, error)); ok {
		return rf(ctx, nodeAddr, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *domain.Command) *domain.CommandResult); ok {
		r0 = rf(ctx, nodeAddr, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CommandResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *domain.Command) string); ok {
		r1 = rf(ctx, nodeAddr, cmd)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, *domain.Command) error); ok {
		r2 = rf(ctx, nodeAddr, cmd)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockTransportPort_SendApplyCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendApplyCommand'
type MockTransportPort_SendApplyCommand_Call struct {
	*mock.Call
}

// SendApplyCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeAddr string
//   - cmd *domain.Command
func (_e *MockTransportPort_Expecter) SendApplyCommand(ctx interface{}, nodeAddr interface{}, cmd interface{}) *MockTransportPort_SendApplyCommand_Call {
	return &MockTransportPort_SendApplyCommand_Call{Call: _e.mock.On("SendApplyCommand", ctx, nodeAddr, cmd)}
}

func (_c *MockTransportPort_SendApplyCommand_Call) Run(run func(ctx context.Context, nodeAddr string, cmd *domain.Command)) *MockTransportPort_SendApplyCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*domain.Command))
	})
	return _c
}

func (_c *MockTransportPort_SendApplyCommand_Call) Return(_a0 *domain.CommandResult, _a1 string, _a2 error) *MockTransportPort_SendApplyCommand_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockTransportPort_SendApplyCommand_Call) RunAndReturn(run func(context.Context, string, *domain.Command) (*domain.CommandResult, string, error)) *MockTransportPort_SendApplyCommand_Call {
	_c.Call.Return(run)
	return _c
}

// SendJoinRequest provides a mock function with given fields: ctx, nodeAddr, request
func (_m *MockTransportPort) SendJoinRequest(ctx context.Context, nodeAddr string, request *ports.JoinRequest) (*ports.JoinResponse, error) {
	ret := _m.Called(ctx, nodeAddr, request)

	if len(ret) == 0 {
		panic("no return value specified for SendJoinRequest")
	}

	var r0 *ports.JoinResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *ports.JoinRequest) (*ports.JoinResponse, error)); ok {
		return rf(ctx, nodeAddr, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *ports.JoinRequest) *ports.JoinResponse); ok {
		r0 = rf(ctx, nodeAddr, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ports.JoinResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *ports.JoinRequest) error); ok {
		r1 = rf(ctx, nodeAddr, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTransportPort_SendJoinRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendJoinRequest'
type MockTransportPort_SendJoinRequest_Call struct {
	*mock.Call
}

// SendJoinRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeAddr string
//   - request *ports.JoinRequest
func (_e *MockTransportPort_Expecter) SendJoinRequest(ctx interface{}, nodeAddr interface{}, request interface{}) *MockTransportPort_SendJoinRequest_Call {
	return &MockTransportPort_SendJoinRequest_Call{Call: _e.mock.On("SendJoinRequest", ctx, nodeAddr, request)}
}

func (_c *MockTransportPort_SendJoinRequest_Call) Run(run func(ctx context.Context, nodeAddr string, request *ports.JoinRequest)) *MockTransportPort_SendJoinRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*ports.JoinRequest))
	})
	return _c
}

func (_c *MockTransportPort_SendJoinRequest_Call) Return(_a0 *ports.JoinResponse, _a1 error) *MockTransportPort_SendJoinRequest_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTransportPort_SendJoinRequest_Call) RunAndReturn(run func(context.Context, string, *ports.JoinRequest) (*ports.JoinResponse, error)) *MockTransportPort_SendJoinRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SendTrigger provides a mock function with given fields: ctx, nodeAddr, trigger
func (_m *MockTransportPort) SendTrigger(ctx context.Context, nodeAddr string, trigger domain.WorkflowTrigger) error {
	ret := _m.Called(ctx, nodeAddr, trigger)

	if len(ret) == 0 {
		panic("no return value specified for SendTrigger")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.WorkflowTrigger) error); ok {
		r0 = rf(ctx, nodeAddr, trigger)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTransportPort_SendTrigger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendTrigger'
type MockTransportPort_SendTrigger_Call struct {
	*mock.Call
}

// SendTrigger is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeAddr string
//   - trigger domain.WorkflowTrigger
func (_e *MockTransportPort_Expecter) SendTrigger(ctx interface{}, nodeAddr interface{}, trigger interface{}) *MockTransportPort_SendTrigger_Call {
	return &MockTransportPort_SendTrigger_Call{Call: _e.mock.On("SendTrigger", ctx, nodeAddr, trigger)}
}

func (_c *MockTransportPort_SendTrigger_Call) Run(run func(ctx context.Context, nodeAddr string, trigger domain.WorkflowTrigger)) *MockTransportPort_SendTrigger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(domain.WorkflowTrigger))
	})
	return _c
}

func (_c *MockTransportPort_SendTrigger_Call) Return(_a0 error) *MockTransportPort_SendTrigger_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTransportPort_SendTrigger_Call) RunAndReturn(run func(context.Context, string, domain.WorkflowTrigger) error) *MockTransportPort_SendTrigger_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTransportPort creates a new instance of MockTransportPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransportPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransportPort {
	mock := &MockTransportPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
