// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: bootstrap.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProposeTokenRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProposedEpoch   uint64                 `protobuf:"varint,1,opt,name=proposed_epoch,json=proposedEpoch,proto3" json:"proposed_epoch,omitempty"`
	ProposerId      string                 `protobuf:"bytes,2,opt,name=proposer_id,json=proposerId,proto3" json:"proposer_id,omitempty"`
	ProposerAddress string                 `protobuf:"bytes,3,opt,name=proposer_address,json=proposerAddress,proto3" json:"proposer_address,omitempty"`
	VoterSetHash    string                 `protobuf:"bytes,4,opt,name=voter_set_hash,json=voterSetHash,proto3" json:"voter_set_hash,omitempty"`
	QuorumSize      int32                  `protobuf:"varint,5,opt,name=quorum_size,json=quorumSize,proto3" json:"quorum_size,omitempty"`
	Mode            int32                  `protobuf:"varint,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Timestamp       int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature       []byte                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	ExpectedEpoch   uint64                 `protobuf:"varint,9,opt,name=expected_epoch,json=expectedEpoch,proto3" json:"expected_epoch,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProposeTokenRequest) Reset() {
	*x = ProposeTokenRequest{}
	mi := &file_bootstrap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeTokenRequest) ProtoMessage() {}

func (x *ProposeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeTokenRequest.ProtoReflect.Descriptor instead.
func (*ProposeTokenRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{0}
}

func (x *ProposeTokenRequest) GetProposedEpoch() uint64 {
	if x != nil {
		return x.ProposedEpoch
	}
	return 0
}

func (x *ProposeTokenRequest) GetProposerId() string {
	if x != nil {
		return x.ProposerId
	}
	return ""
}

func (x *ProposeTokenRequest) GetProposerAddress() string {
	if x != nil {
		return x.ProposerAddress
	}
	return ""
}

func (x *ProposeTokenRequest) GetVoterSetHash() string {
	if x != nil {
		return x.VoterSetHash
	}
	return ""
}

func (x *ProposeTokenRequest) GetQuorumSize() int32 {
	if x != nil {
		return x.QuorumSize
	}
	return 0
}

func (x *ProposeTokenRequest) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ProposeTokenRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProposeTokenRequest) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ProposeTokenRequest) GetExpectedEpoch() uint64 {
	if x != nil {
		return x.ExpectedEpoch
	}
	return 0
}

type ProposeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProposedEpoch uint64                 `protobuf:"varint,1,opt,name=proposed_epoch,json=proposedEpoch,proto3" json:"proposed_epoch,omitempty"`
	VoterId       string                 `protobuf:"bytes,2,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,3,opt,name=accepted,proto3" json:"accepted,omitempty"`
	CurrentEpoch  uint64                 `protobuf:"varint,4,opt,name=current_epoch,json=currentEpoch,proto3" json:"current_epoch,omitempty"`
	RejectReason  string                 `protobuf:"bytes,5,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProposeTokenResponse) Reset() {
	*x = ProposeTokenResponse{}
	mi := &file_bootstrap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProposeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposeTokenResponse) ProtoMessage() {}

func (x *ProposeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposeTokenResponse.ProtoReflect.Descriptor instead.
func (*ProposeTokenResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{1}
}

func (x *ProposeTokenResponse) GetProposedEpoch() uint64 {
	if x != nil {
		return x.ProposedEpoch
	}
	return 0
}

func (x *ProposeTokenResponse) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

func (x *ProposeTokenResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ProposeTokenResponse) GetCurrentEpoch() uint64 {
	if x != nil {
		return x.CurrentEpoch
	}
	return 0
}

func (x *ProposeTokenResponse) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *ProposeTokenResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ProposeTokenResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VoteRequestProto struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CandidateId      string                 `protobuf:"bytes,1,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	CandidateOrdinal int32                  `protobuf:"varint,2,opt,name=candidate_ordinal,json=candidateOrdinal,proto3" json:"candidate_ordinal,omitempty"`
	ElectionReason   string                 `protobuf:"bytes,3,opt,name=election_reason,json=electionReason,proto3" json:"election_reason,omitempty"`
	Timestamp        int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	VoterSetHash     []byte                 `protobuf:"bytes,5,opt,name=voter_set_hash,json=voterSetHash,proto3" json:"voter_set_hash,omitempty"`
	RequiredQuorum   int32                  `protobuf:"varint,6,opt,name=required_quorum,json=requiredQuorum,proto3" json:"required_quorum,omitempty"`
	Signature        []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VoteRequestProto) Reset() {
	*x = VoteRequestProto{}
	mi := &file_bootstrap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequestProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequestProto) ProtoMessage() {}

func (x *VoteRequestProto) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequestProto.ProtoReflect.Descriptor instead.
func (*VoteRequestProto) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{2}
}

func (x *VoteRequestProto) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *VoteRequestProto) GetCandidateOrdinal() int32 {
	if x != nil {
		return x.CandidateOrdinal
	}
	return 0
}

func (x *VoteRequestProto) GetElectionReason() string {
	if x != nil {
		return x.ElectionReason
	}
	return ""
}

func (x *VoteRequestProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *VoteRequestProto) GetVoterSetHash() []byte {
	if x != nil {
		return x.VoterSetHash
	}
	return nil
}

func (x *VoteRequestProto) GetRequiredQuorum() int32 {
	if x != nil {
		return x.RequiredQuorum
	}
	return 0
}

func (x *VoteRequestProto) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type VoteResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGranted   bool                   `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	VoterId       string                 `protobuf:"bytes,3,opt,name=voter_id,json=voterId,proto3" json:"voter_id,omitempty"`
	VoterSetHash  []byte                 `protobuf:"bytes,4,opt,name=voter_set_hash,json=voterSetHash,proto3" json:"voter_set_hash,omitempty"`
	Signature     []byte                 `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponseProto) Reset() {
	*x = VoteResponseProto{}
	mi := &file_bootstrap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponseProto) ProtoMessage() {}

func (x *VoteResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponseProto.ProtoReflect.Descriptor instead.
func (*VoteResponseProto) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{3}
}

func (x *VoteResponseProto) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *VoteResponseProto) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VoteResponseProto) GetVoterId() string {
	if x != nil {
		return x.VoterId
	}
	return ""
}

func (x *VoteResponseProto) GetVoterSetHash() []byte {
	if x != nil {
		return x.VoterSetHash
	}
	return nil
}

func (x *VoteResponseProto) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type GetClusterMetaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterMetaRequest) Reset() {
	*x = GetClusterMetaRequest{}
	mi := &file_bootstrap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterMetaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterMetaRequest) ProtoMessage() {}

func (x *GetClusterMetaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterMetaRequest.ProtoReflect.Descriptor instead.
func (*GetClusterMetaRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{4}
}

type ClusterMetaProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	ClusterUuid   string                 `protobuf:"bytes,2,opt,name=cluster_uuid,json=clusterUuid,proto3" json:"cluster_uuid,omitempty"`
	ServerId      string                 `protobuf:"bytes,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	ServerAddress string                 `protobuf:"bytes,4,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Ordinal       int32                  `protobuf:"varint,5,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	State         int32                  `protobuf:"varint,6,opt,name=state,proto3" json:"state,omitempty"`
	BootstrapTime int64                  `protobuf:"varint,7,opt,name=bootstrap_time,json=bootstrapTime,proto3" json:"bootstrap_time,omitempty"`
	Checksum      uint32                 `protobuf:"varint,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterMetaProto) Reset() {
	*x = ClusterMetaProto{}
	mi := &file_bootstrap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterMetaProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterMetaProto) ProtoMessage() {}

func (x *ClusterMetaProto) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterMetaProto.ProtoReflect.Descriptor instead.
func (*ClusterMetaProto) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{5}
}

func (x *ClusterMetaProto) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClusterMetaProto) GetClusterUuid() string {
	if x != nil {
		return x.ClusterUuid
	}
	return ""
}

func (x *ClusterMetaProto) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ClusterMetaProto) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ClusterMetaProto) GetOrdinal() int32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ClusterMetaProto) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ClusterMetaProto) GetBootstrapTime() int64 {
	if x != nil {
		return x.BootstrapTime
	}
	return 0
}

func (x *ClusterMetaProto) GetChecksum() uint32 {
	if x != nil {
		return x.Checksum
	}
	return 0
}

type GetFencingEpochRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFencingEpochRequest) Reset() {
	*x = GetFencingEpochRequest{}
	mi := &file_bootstrap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFencingEpochRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFencingEpochRequest) ProtoMessage() {}

func (x *GetFencingEpochRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFencingEpochRequest.ProtoReflect.Descriptor instead.
func (*GetFencingEpochRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{6}
}

type GetFencingEpochResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFencingEpochResponse) Reset() {
	*x = GetFencingEpochResponse{}
	mi := &file_bootstrap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFencingEpochResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFencingEpochResponse) ProtoMessage() {}

func (x *GetFencingEpochResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFencingEpochResponse.ProtoReflect.Descriptor instead.
func (*GetFencingEpochResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{7}
}

func (x *GetFencingEpochResponse) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type GetLastIndexRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastIndexRequest) Reset() {
	*x = GetLastIndexRequest{}
	mi := &file_bootstrap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastIndexRequest) ProtoMessage() {}

func (x *GetLastIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastIndexRequest.ProtoReflect.Descriptor instead.
func (*GetLastIndexRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{8}
}

type GetLastIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastIndex     uint64                 `protobuf:"varint,1,opt,name=last_index,json=lastIndex,proto3" json:"last_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastIndexResponse) Reset() {
	*x = GetLastIndexResponse{}
	mi := &file_bootstrap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastIndexResponse) ProtoMessage() {}

func (x *GetLastIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastIndexResponse.ProtoReflect.Descriptor instead.
func (*GetLastIndexResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{9}
}

func (x *GetLastIndexResponse) GetLastIndex() uint64 {
	if x != nil {
		return x.LastIndex
	}
	return 0
}

type TokenUsageNotificationProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       uint32                 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	TokenHash     string                 `protobuf:"bytes,2,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	UsedAt        int64                  `protobuf:"varint,3,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`
	UsedBy        string                 `protobuf:"bytes,4,opt,name=used_by,json=usedBy,proto3" json:"used_by,omitempty"`
	NewEpoch      uint64                 `protobuf:"varint,5,opt,name=new_epoch,json=newEpoch,proto3" json:"new_epoch,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SenderId      string                 `protobuf:"bytes,7,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Signature     string                 `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsageNotificationProto) Reset() {
	*x = TokenUsageNotificationProto{}
	mi := &file_bootstrap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageNotificationProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageNotificationProto) ProtoMessage() {}

func (x *TokenUsageNotificationProto) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageNotificationProto.ProtoReflect.Descriptor instead.
func (*TokenUsageNotificationProto) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{10}
}

func (x *TokenUsageNotificationProto) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TokenUsageNotificationProto) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *TokenUsageNotificationProto) GetUsedAt() int64 {
	if x != nil {
		return x.UsedAt
	}
	return 0
}

func (x *TokenUsageNotificationProto) GetUsedBy() string {
	if x != nil {
		return x.UsedBy
	}
	return ""
}

func (x *TokenUsageNotificationProto) GetNewEpoch() uint64 {
	if x != nil {
		return x.NewEpoch
	}
	return 0
}

func (x *TokenUsageNotificationProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TokenUsageNotificationProto) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *TokenUsageNotificationProto) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type NotifyTokenUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged  bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyTokenUsageResponse) Reset() {
	*x = NotifyTokenUsageResponse{}
	mi := &file_bootstrap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyTokenUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyTokenUsageResponse) ProtoMessage() {}

func (x *NotifyTokenUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyTokenUsageResponse.ProtoReflect.Descriptor instead.
func (*NotifyTokenUsageResponse) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{11}
}

func (x *NotifyTokenUsageResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

type GetTokenUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenHash     string                 `protobuf:"bytes,1,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenUsageRequest) Reset() {
	*x = GetTokenUsageRequest{}
	mi := &file_bootstrap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenUsageRequest) ProtoMessage() {}

func (x *GetTokenUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenUsageRequest.ProtoReflect.Descriptor instead.
func (*GetTokenUsageRequest) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{12}
}

func (x *GetTokenUsageRequest) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

type TokenUsageResponseProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Used          bool                   `protobuf:"varint,1,opt,name=used,proto3" json:"used,omitempty"`
	UsedBy        string                 `protobuf:"bytes,2,opt,name=used_by,json=usedBy,proto3" json:"used_by,omitempty"`
	UsedAt        int64                  `protobuf:"varint,3,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`
	TokenHash     string                 `protobuf:"bytes,4,opt,name=token_hash,json=tokenHash,proto3" json:"token_hash,omitempty"`
	ResponderId   string                 `protobuf:"bytes,5,opt,name=responder_id,json=responderId,proto3" json:"responder_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature     string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsageResponseProto) Reset() {
	*x = TokenUsageResponseProto{}
	mi := &file_bootstrap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageResponseProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageResponseProto) ProtoMessage() {}

func (x *TokenUsageResponseProto) ProtoReflect() protoreflect.Message {
	mi := &file_bootstrap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageResponseProto.ProtoReflect.Descriptor instead.
func (*TokenUsageResponseProto) Descriptor() ([]byte, []int) {
	return file_bootstrap_proto_rawDescGZIP(), []int{13}
}

func (x *TokenUsageResponseProto) GetUsed() bool {
	if x != nil {
		return x.Used
	}
	return false
}

func (x *TokenUsageResponseProto) GetUsedBy() string {
	if x != nil {
		return x.UsedBy
	}
	return ""
}

func (x *TokenUsageResponseProto) GetUsedAt() int64 {
	if x != nil {
		return x.UsedAt
	}
	return 0
}

func (x *TokenUsageResponseProto) GetTokenHash() string {
	if x != nil {
		return x.TokenHash
	}
	return ""
}

func (x *TokenUsageResponseProto) GetResponderId() string {
	if x != nil {
		return x.ResponderId
	}
	return ""
}

func (x *TokenUsageResponseProto) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TokenUsageResponseProto) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

var File_bootstrap_proto protoreflect.FileDescriptor

const file_bootstrap_proto_rawDesc = "" +
	"\n" +
	"\x0fbootstrap.proto\x12\tbootstrap\"\xc6\x02\n" +
	"\x13ProposeTokenRequest\x12%\n" +
	"\x0eproposed_epoch\x18\x01 \x01(\x04R\rproposedEpoch\x12\x1f\n" +
	"\vproposer_id\x18\x02 \x01(\tR\n" +
	"proposerId\x12)\n" +
	"\x10proposer_address\x18\x03 \x01(\tR\x0fproposerAddress\x12$\n" +
	"\x0evoter_set_hash\x18\x04 \x01(\tR\fvoterSetHash\x12\x1f\n" +
	"\vquorum_size\x18\x05 \x01(\x05R\n" +
	"quorumSize\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\x05R\x04mode\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12%\n" +
	"\x0eexpected_epoch\x18\t \x01(\x04R\rexpectedEpoch\"\xfa\x01\n" +
	"\x14ProposeTokenResponse\x12%\n" +
	"\x0eproposed_epoch\x18\x01 \x01(\x04R\rproposedEpoch\x12\x19\n" +
	"\bvoter_id\x18\x02 \x01(\tR\avoterId\x12\x1a\n" +
	"\baccepted\x18\x03 \x01(\bR\baccepted\x12#\n" +
	"\rcurrent_epoch\x18\x04 \x01(\x04R\fcurrentEpoch\x12#\n" +
	"\rreject_reason\x18\x05 \x01(\tR\frejectReason\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\x96\x02\n" +
	"\x10VoteRequestProto\x12!\n" +
	"\fcandidate_id\x18\x01 \x01(\tR\vcandidateId\x12+\n" +
	"\x11candidate_ordinal\x18\x02 \x01(\x05R\x10candidateOrdinal\x12'\n" +
	"\x0felection_reason\x18\x03 \x01(\tR\x0eelectionReason\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12$\n" +
	"\x0evoter_set_hash\x18\x05 \x01(\fR\fvoterSetHash\x12'\n" +
	"\x0frequired_quorum\x18\x06 \x01(\x05R\x0erequiredQuorum\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"\xad\x01\n" +
	"\x11VoteResponseProto\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x19\n" +
	"\bvoter_id\x18\x03 \x01(\tR\avoterId\x12$\n" +
	"\x0evoter_set_hash\x18\x04 \x01(\fR\fvoterSetHash\x12\x1c\n" +
	"\tsignature\x18\x05 \x01(\fR\tsignature\"\x17\n" +
	"\x15GetClusterMetaRequest\"\x86\x02\n" +
	"\x10ClusterMetaProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12!\n" +
	"\fcluster_uuid\x18\x02 \x01(\tR\vclusterUuid\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\tR\bserverId\x12%\n" +
	"\x0eserver_address\x18\x04 \x01(\tR\rserverAddress\x12\x18\n" +
	"\aordinal\x18\x05 \x01(\x05R\aordinal\x12\x14\n" +
	"\x05state\x18\x06 \x01(\x05R\x05state\x12%\n" +
	"\x0ebootstrap_time\x18\a \x01(\x03R\rbootstrapTime\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\rR\bchecksum\"\x18\n" +
	"\x16GetFencingEpochRequest\"/\n" +
	"\x17GetFencingEpochResponse\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\"\x15\n" +
	"\x13GetLastIndexRequest\"5\n" +
	"\x14GetLastIndexResponse\x12\x1d\n" +
	"\n" +
	"last_index\x18\x01 \x01(\x04R\tlastIndex\"\xfe\x01\n" +
	"\x1bTokenUsageNotificationProto\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x02 \x01(\tR\ttokenHash\x12\x17\n" +
	"\aused_at\x18\x03 \x01(\x03R\x06usedAt\x12\x17\n" +
	"\aused_by\x18\x04 \x01(\tR\x06usedBy\x12\x1b\n" +
	"\tnew_epoch\x18\x05 \x01(\x04R\bnewEpoch\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tsender_id\x18\a \x01(\tR\bsenderId\x12\x1c\n" +
	"\tsignature\x18\b \x01(\tR\tsignature\">\n" +
	"\x18NotifyTokenUsageResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\"5\n" +
	"\x14GetTokenUsageRequest\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x01 \x01(\tR\ttokenHash\"\xdd\x01\n" +
	"\x17TokenUsageResponseProto\x12\x12\n" +
	"\x04used\x18\x01 \x01(\bR\x04used\x12\x17\n" +
	"\aused_by\x18\x02 \x01(\tR\x06usedBy\x12\x17\n" +
	"\aused_at\x18\x03 \x01(\x03R\x06usedAt\x12\x1d\n" +
	"\n" +
	"token_hash\x18\x04 \x01(\tR\ttokenHash\x12!\n" +
	"\fresponder_id\x18\x05 \x01(\tR\vresponderId\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x1c\n" +
	"\tsignature\x18\a \x01(\tR\tsignature2\xe0\x04\n" +
	"\x10BootstrapService\x12O\n" +
	"\fProposeToken\x12\x1e.bootstrap.ProposeTokenRequest\x1a\x1f.bootstrap.ProposeTokenResponse\x12H\n" +
	"\vRequestVote\x12\x1b.bootstrap.VoteRequestProto\x1a\x1c.bootstrap.VoteResponseProto\x12O\n" +
	"\x0eGetClusterMeta\x12 .bootstrap.GetClusterMetaRequest\x1a\x1b.bootstrap.ClusterMetaProto\x12X\n" +
	"\x0fGetFencingEpoch\x12!.bootstrap.GetFencingEpochRequest\x1a\".bootstrap.GetFencingEpochResponse\x12O\n" +
	"\fGetLastIndex\x12\x1e.bootstrap.GetLastIndexRequest\x1a\x1f.bootstrap.GetLastIndexResponse\x12_\n" +
	"\x10NotifyTokenUsage\x12&.bootstrap.TokenUsageNotificationProto\x1a#.bootstrap.NotifyTokenUsageResponse\x12T\n" +
	"\rGetTokenUsage\x12\x1f.bootstrap.GetTokenUsageRequest\x1a\".bootstrap.TokenUsageResponseProtoB+Z)github.com/eleven-am/graft/internal/protob\x06proto3"

var (
	file_bootstrap_proto_rawDescOnce sync.Once
	file_bootstrap_proto_rawDescData []byte
)

func file_bootstrap_proto_rawDescGZIP() []byte {
	file_bootstrap_proto_rawDescOnce.Do(func() {
		file_bootstrap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bootstrap_proto_rawDesc), len(file_bootstrap_proto_rawDesc)))
	})
	return file_bootstrap_proto_rawDescData
}

var file_bootstrap_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_bootstrap_proto_goTypes = []any{
	(*ProposeTokenRequest)(nil),         // 0: bootstrap.ProposeTokenRequest
	(*ProposeTokenResponse)(nil),        // 1: bootstrap.ProposeTokenResponse
	(*VoteRequestProto)(nil),            // 2: bootstrap.VoteRequestProto
	(*VoteResponseProto)(nil),           // 3: bootstrap.VoteResponseProto
	(*GetClusterMetaRequest)(nil),       // 4: bootstrap.GetClusterMetaRequest
	(*ClusterMetaProto)(nil),            // 5: bootstrap.ClusterMetaProto
	(*GetFencingEpochRequest)(nil),      // 6: bootstrap.GetFencingEpochRequest
	(*GetFencingEpochResponse)(nil),     // 7: bootstrap.GetFencingEpochResponse
	(*GetLastIndexRequest)(nil),         // 8: bootstrap.GetLastIndexRequest
	(*GetLastIndexResponse)(nil),        // 9: bootstrap.GetLastIndexResponse
	(*TokenUsageNotificationProto)(nil), // 10: bootstrap.TokenUsageNotificationProto
	(*NotifyTokenUsageResponse)(nil),    // 11: bootstrap.NotifyTokenUsageResponse
	(*GetTokenUsageRequest)(nil),        // 12: bootstrap.GetTokenUsageRequest
	(*TokenUsageResponseProto)(nil),     // 13: bootstrap.TokenUsageResponseProto
}
var file_bootstrap_proto_depIdxs = []int32{
	0,  // 0: bootstrap.BootstrapService.ProposeToken:input_type -> bootstrap.ProposeTokenRequest
	2,  // 1: bootstrap.BootstrapService.RequestVote:input_type -> bootstrap.VoteRequestProto
	4,  // 2: bootstrap.BootstrapService.GetClusterMeta:input_type -> bootstrap.GetClusterMetaRequest
	6,  // 3: bootstrap.BootstrapService.GetFencingEpoch:input_type -> bootstrap.GetFencingEpochRequest
	8,  // 4: bootstrap.BootstrapService.GetLastIndex:input_type -> bootstrap.GetLastIndexRequest
	10, // 5: bootstrap.BootstrapService.NotifyTokenUsage:input_type -> bootstrap.TokenUsageNotificationProto
	12, // 6: bootstrap.BootstrapService.GetTokenUsage:input_type -> bootstrap.GetTokenUsageRequest
	1,  // 7: bootstrap.BootstrapService.ProposeToken:output_type -> bootstrap.ProposeTokenResponse
	3,  // 8: bootstrap.BootstrapService.RequestVote:output_type -> bootstrap.VoteResponseProto
	5,  // 9: bootstrap.BootstrapService.GetClusterMeta:output_type -> bootstrap.ClusterMetaProto
	7,  // 10: bootstrap.BootstrapService.GetFencingEpoch:output_type -> bootstrap.GetFencingEpochResponse
	9,  // 11: bootstrap.BootstrapService.GetLastIndex:output_type -> bootstrap.GetLastIndexResponse
	11, // 12: bootstrap.BootstrapService.NotifyTokenUsage:output_type -> bootstrap.NotifyTokenUsageResponse
	13, // 13: bootstrap.BootstrapService.GetTokenUsage:output_type -> bootstrap.TokenUsageResponseProto
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_bootstrap_proto_init() }
func file_bootstrap_proto_init() {
	if File_bootstrap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bootstrap_proto_rawDesc), len(file_bootstrap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bootstrap_proto_goTypes,
		DependencyIndexes: file_bootstrap_proto_depIdxs,
		MessageInfos:      file_bootstrap_proto_msgTypes,
	}.Build()
	File_bootstrap_proto = out.File
	file_bootstrap_proto_goTypes = nil
	file_bootstrap_proto_depIdxs = nil
}
