// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.2
// source: graft.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_graft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeConfig) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type WorkflowTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	InitialNodes  []*NodeConfig          `protobuf:"bytes,2,rep,name=initial_nodes,json=initialNodes,proto3" json:"initial_nodes,omitempty"`
	InitialState  []byte                 `protobuf:"bytes,3,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTrigger) Reset() {
	*x = WorkflowTrigger{}
	mi := &file_graft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTrigger) ProtoMessage() {}

func (x *WorkflowTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTrigger.ProtoReflect.Descriptor instead.
func (*WorkflowTrigger) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowTrigger) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowTrigger) GetInitialNodes() []*NodeConfig {
	if x != nil {
		return x.InitialNodes
	}
	return nil
}

func (x *WorkflowTrigger) GetInitialState() []byte {
	if x != nil {
		return x.InitialState
	}
	return nil
}

func (x *WorkflowTrigger) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trigger       *WorkflowTrigger       `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_graft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerRequest) GetTrigger() *WorkflowTrigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_graft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_graft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *JoinRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_graft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ApplyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       []byte                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyRequest) Reset() {
	*x = ApplyRequest{}
	mi := &file_graft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyRequest) ProtoMessage() {}

func (x *ApplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyRequest.ProtoReflect.Descriptor instead.
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{6}
}

func (x *ApplyRequest) GetCommand() []byte {
	if x != nil {
		return x.Command
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          uint32                 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RequestId     string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_graft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{7}
}

func (x *Event) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Event) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Event) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Event) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Event) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Event) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ApplyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	Events        []*Event               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	LeaderId      string                 `protobuf:"bytes,5,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	LeaderAddr    string                 `protobuf:"bytes,6,opt,name=leader_addr,json=leaderAddr,proto3" json:"leader_addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyResponse) Reset() {
	*x = ApplyResponse{}
	mi := &file_graft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyResponse) ProtoMessage() {}

func (x *ApplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyResponse.ProtoReflect.Descriptor instead.
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{8}
}

func (x *ApplyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ApplyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ApplyResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ApplyResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ApplyResponse) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *ApplyResponse) GetLeaderAddr() string {
	if x != nil {
		return x.LeaderAddr
	}
	return ""
}

type LoadUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActiveWorkflows int32                  `protobuf:"varint,2,opt,name=active_workflows,json=activeWorkflows,proto3" json:"active_workflows,omitempty"`
	TotalWeight     float64                `protobuf:"fixed64,3,opt,name=total_weight,json=totalWeight,proto3" json:"total_weight,omitempty"`
	RecentLatencyMs float64                `protobuf:"fixed64,4,opt,name=recent_latency_ms,json=recentLatencyMs,proto3" json:"recent_latency_ms,omitempty"`
	RecentErrorRate float64                `protobuf:"fixed64,5,opt,name=recent_error_rate,json=recentErrorRate,proto3" json:"recent_error_rate,omitempty"`
	// Deprecated: capacity was previously used; keep for backward compatibility
	Capacity  float64 `protobuf:"fixed64,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Timestamp int64   `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Preferred: normalized pressure (cpu+mem) in range [0..2]
	Pressure      float64 `protobuf:"fixed64,8,opt,name=pressure,proto3" json:"pressure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadUpdate) Reset() {
	*x = LoadUpdate{}
	mi := &file_graft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadUpdate) ProtoMessage() {}

func (x *LoadUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadUpdate.ProtoReflect.Descriptor instead.
func (*LoadUpdate) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{9}
}

func (x *LoadUpdate) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LoadUpdate) GetActiveWorkflows() int32 {
	if x != nil {
		return x.ActiveWorkflows
	}
	return 0
}

func (x *LoadUpdate) GetTotalWeight() float64 {
	if x != nil {
		return x.TotalWeight
	}
	return 0
}

func (x *LoadUpdate) GetRecentLatencyMs() float64 {
	if x != nil {
		return x.RecentLatencyMs
	}
	return 0
}

func (x *LoadUpdate) GetRecentErrorRate() float64 {
	if x != nil {
		return x.RecentErrorRate
	}
	return 0
}

func (x *LoadUpdate) GetCapacity() float64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *LoadUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LoadUpdate) GetPressure() float64 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_graft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_graft_proto protoreflect.FileDescriptor

const file_graft_proto_rawDesc = "" +
	"\n" +
	"\vgraft.proto\x12\x05graft\"8\n" +
	"\n" +
	"NodeConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\"\x8e\x02\n" +
	"\x0fWorkflowTrigger\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x126\n" +
	"\rinitial_nodes\x18\x02 \x03(\v2\x11.graft.NodeConfigR\finitialNodes\x12#\n" +
	"\rinitial_state\x18\x03 \x01(\fR\finitialState\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.graft.WorkflowTrigger.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0eTriggerRequest\x120\n" +
	"\atrigger\x18\x01 \x01(\v2\x16.graft.WorkflowTriggerR\atrigger\"E\n" +
	"\x0fTriggerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcf\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12<\n" +
	"\bmetadata\x18\x04 \x03(\v2 .graft.JoinRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\fJoinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"\fApplyRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\fR\acommand\"\x9d\x01\n" +
	"\x05Event\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\"\xbd\x01\n" +
	"\rApplyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\x12$\n" +
	"\x06events\x18\x04 \x03(\v2\f.graft.EventR\x06events\x12\x1b\n" +
	"\tleader_id\x18\x05 \x01(\tR\bleaderId\x12\x1f\n" +
	"\vleader_addr\x18\x06 \x01(\tR\n" +
	"leaderAddr\"\xa1\x02\n" +
	"\n" +
	"LoadUpdate\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12)\n" +
	"\x10active_workflows\x18\x02 \x01(\x05R\x0factiveWorkflows\x12!\n" +
	"\ftotal_weight\x18\x03 \x01(\x01R\vtotalWeight\x12*\n" +
	"\x11recent_latency_ms\x18\x04 \x01(\x01R\x0frecentLatencyMs\x12*\n" +
	"\x11recent_error_rate\x18\x05 \x01(\x01R\x0frecentErrorRate\x12\x1a\n" +
	"\bcapacity\x18\x06 \x01(\x01R\bcapacity\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1a\n" +
	"\bpressure\x18\b \x01(\x01R\bpressure\"/\n" +
	"\x03Ack\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xed\x01\n" +
	"\tGraftNode\x12?\n" +
	"\x0eProcessTrigger\x12\x15.graft.TriggerRequest\x1a\x16.graft.TriggerResponse\x126\n" +
	"\vRequestJoin\x12\x12.graft.JoinRequest\x1a\x13.graft.JoinResponse\x129\n" +
	"\fApplyCommand\x12\x13.graft.ApplyRequest\x1a\x14.graft.ApplyResponse\x12,\n" +
	"\vPublishLoad\x12\x11.graft.LoadUpdate\x1a\n" +
	".graft.AckB+Z)github.com/eleven-am/graft/internal/protob\x06proto3"

var (
	file_graft_proto_rawDescOnce sync.Once
	file_graft_proto_rawDescData []byte
)

func file_graft_proto_rawDescGZIP() []byte {
	file_graft_proto_rawDescOnce.Do(func() {
		file_graft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graft_proto_rawDesc), len(file_graft_proto_rawDesc)))
	})
	return file_graft_proto_rawDescData
}

var file_graft_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_graft_proto_goTypes = []any{
	(*NodeConfig)(nil),      // 0: graft.NodeConfig
	(*WorkflowTrigger)(nil), // 1: graft.WorkflowTrigger
	(*TriggerRequest)(nil),  // 2: graft.TriggerRequest
	(*TriggerResponse)(nil), // 3: graft.TriggerResponse
	(*JoinRequest)(nil),     // 4: graft.JoinRequest
	(*JoinResponse)(nil),    // 5: graft.JoinResponse
	(*ApplyRequest)(nil),    // 6: graft.ApplyRequest
	(*Event)(nil),           // 7: graft.Event
	(*ApplyResponse)(nil),   // 8: graft.ApplyResponse
	(*LoadUpdate)(nil),      // 9: graft.LoadUpdate
	(*Ack)(nil),             // 10: graft.Ack
	nil,                     // 11: graft.WorkflowTrigger.MetadataEntry
	nil,                     // 12: graft.JoinRequest.MetadataEntry
}
var file_graft_proto_depIdxs = []int32{
	0,  // 0: graft.WorkflowTrigger.initial_nodes:type_name -> graft.NodeConfig
	11, // 1: graft.WorkflowTrigger.metadata:type_name -> graft.WorkflowTrigger.MetadataEntry
	1,  // 2: graft.TriggerRequest.trigger:type_name -> graft.WorkflowTrigger
	12, // 3: graft.JoinRequest.metadata:type_name -> graft.JoinRequest.MetadataEntry
	7,  // 4: graft.ApplyResponse.events:type_name -> graft.Event
	2,  // 5: graft.GraftNode.ProcessTrigger:input_type -> graft.TriggerRequest
	4,  // 6: graft.GraftNode.RequestJoin:input_type -> graft.JoinRequest
	6,  // 7: graft.GraftNode.ApplyCommand:input_type -> graft.ApplyRequest
	9,  // 8: graft.GraftNode.PublishLoad:input_type -> graft.LoadUpdate
	3,  // 9: graft.GraftNode.ProcessTrigger:output_type -> graft.TriggerResponse
	5,  // 10: graft.GraftNode.RequestJoin:output_type -> graft.JoinResponse
	8,  // 11: graft.GraftNode.ApplyCommand:output_type -> graft.ApplyResponse
	10, // 12: graft.GraftNode.PublishLoad:output_type -> graft.Ack
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_graft_proto_init() }
func file_graft_proto_init() {
	if File_graft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graft_proto_rawDesc), len(file_graft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graft_proto_goTypes,
		DependencyIndexes: file_graft_proto_depIdxs,
		MessageInfos:      file_graft_proto_msgTypes,
	}.Build()
	File_graft_proto = out.File
	file_graft_proto_goTypes = nil
	file_graft_proto_depIdxs = nil
}
