// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: graft.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Config        []byte                 `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeConfig) Reset() {
	*x = NodeConfig{}
	mi := &file_graft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeConfig) ProtoMessage() {}

func (x *NodeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeConfig.ProtoReflect.Descriptor instead.
func (*NodeConfig) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{0}
}

func (x *NodeConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeConfig) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

type WorkflowTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	InitialNodes  []*NodeConfig          `protobuf:"bytes,2,rep,name=initial_nodes,json=initialNodes,proto3" json:"initial_nodes,omitempty"`
	InitialState  []byte                 `protobuf:"bytes,3,opt,name=initial_state,json=initialState,proto3" json:"initial_state,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTrigger) Reset() {
	*x = WorkflowTrigger{}
	mi := &file_graft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTrigger) ProtoMessage() {}

func (x *WorkflowTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTrigger.ProtoReflect.Descriptor instead.
func (*WorkflowTrigger) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowTrigger) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *WorkflowTrigger) GetInitialNodes() []*NodeConfig {
	if x != nil {
		return x.InitialNodes
	}
	return nil
}

func (x *WorkflowTrigger) GetInitialState() []byte {
	if x != nil {
		return x.InitialState
	}
	return nil
}

func (x *WorkflowTrigger) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TriggerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trigger       *WorkflowTrigger       `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_graft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerRequest) GetTrigger() *WorkflowTrigger {
	if x != nil {
		return x.Trigger
	}
	return nil
}

type TriggerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_graft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRequest) Reset() {
	*x = JoinRequest{}
	mi := &file_graft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRequest) ProtoMessage() {}

func (x *JoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRequest.ProtoReflect.Descriptor instead.
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *JoinRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *JoinRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type JoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinResponse) Reset() {
	*x = JoinResponse{}
	mi := &file_graft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinResponse) ProtoMessage() {}

func (x *JoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_graft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinResponse.ProtoReflect.Descriptor instead.
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return file_graft_proto_rawDescGZIP(), []int{5}
}

func (x *JoinResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *JoinResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *JoinResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_graft_proto protoreflect.FileDescriptor

const file_graft_proto_rawDesc = "" +
	"\n" +
	"\vgraft.proto\x12\x05graft\"8\n" +
	"\n" +
	"NodeConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06config\x18\x02 \x01(\fR\x06config\"\x8e\x02\n" +
	"\x0fWorkflowTrigger\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x126\n" +
	"\rinitial_nodes\x18\x02 \x03(\v2\x11.graft.NodeConfigR\finitialNodes\x12#\n" +
	"\rinitial_state\x18\x03 \x01(\fR\finitialState\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.graft.WorkflowTrigger.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"B\n" +
	"\x0eTriggerRequest\x120\n" +
	"\atrigger\x18\x01 \x01(\v2\x16.graft.WorkflowTriggerR\atrigger\"E\n" +
	"\x0fTriggerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xcf\x01\n" +
	"\vJoinRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12<\n" +
	"\bmetadata\x18\x04 \x03(\v2 .graft.JoinRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"]\n" +
	"\fJoinResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\x84\x01\n" +
	"\tGraftNode\x12?\n" +
	"\x0eProcessTrigger\x12\x15.graft.TriggerRequest\x1a\x16.graft.TriggerResponse\x126\n" +
	"\vRequestJoin\x12\x12.graft.JoinRequest\x1a\x13.graft.JoinResponseB+Z)github.com/eleven-am/graft/internal/protob\x06proto3"

var (
	file_graft_proto_rawDescOnce sync.Once
	file_graft_proto_rawDescData []byte
)

func file_graft_proto_rawDescGZIP() []byte {
	file_graft_proto_rawDescOnce.Do(func() {
		file_graft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graft_proto_rawDesc), len(file_graft_proto_rawDesc)))
	})
	return file_graft_proto_rawDescData
}

var file_graft_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_graft_proto_goTypes = []any{
	(*NodeConfig)(nil),      // 0: graft.NodeConfig
	(*WorkflowTrigger)(nil), // 1: graft.WorkflowTrigger
	(*TriggerRequest)(nil),  // 2: graft.TriggerRequest
	(*TriggerResponse)(nil), // 3: graft.TriggerResponse
	(*JoinRequest)(nil),     // 4: graft.JoinRequest
	(*JoinResponse)(nil),    // 5: graft.JoinResponse
	nil,                     // 6: graft.WorkflowTrigger.MetadataEntry
	nil,                     // 7: graft.JoinRequest.MetadataEntry
}
var file_graft_proto_depIdxs = []int32{
	0, // 0: graft.WorkflowTrigger.initial_nodes:type_name -> graft.NodeConfig
	6, // 1: graft.WorkflowTrigger.metadata:type_name -> graft.WorkflowTrigger.MetadataEntry
	1, // 2: graft.TriggerRequest.trigger:type_name -> graft.WorkflowTrigger
	7, // 3: graft.JoinRequest.metadata:type_name -> graft.JoinRequest.MetadataEntry
	2, // 4: graft.GraftNode.ProcessTrigger:input_type -> graft.TriggerRequest
	4, // 5: graft.GraftNode.RequestJoin:input_type -> graft.JoinRequest
	3, // 6: graft.GraftNode.ProcessTrigger:output_type -> graft.TriggerResponse
	5, // 7: graft.GraftNode.RequestJoin:output_type -> graft.JoinResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_graft_proto_init() }
func file_graft_proto_init() {
	if File_graft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graft_proto_rawDesc), len(file_graft_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_graft_proto_goTypes,
		DependencyIndexes: file_graft_proto_depIdxs,
		MessageInfos:      file_graft_proto_msgTypes,
	}.Build()
	File_graft_proto = out.File
	file_graft_proto_goTypes = nil
	file_graft_proto_depIdxs = nil
}
