with-expecter: true
all: false
keeptree: false
resolve-type-alias: false
disable-version-string: true
issue-845-fix: true
dir: .
mockname: "Mock{{.InterfaceName}}"
outpkg: mocks
filename: "{{.InterfaceName | snakecase }}_mock.go"

packages:
  github.com/eleven-am/graft/internal/ports:
    config:
      dir: "./internal/mocks"
    interfaces:
      StoragePort:
      Transaction:
      EventManager:
      LoadBalancer:
      NodeRegistryPort:
      RaftNode:
      QueuePort:
  github.com/eleven-am/graft/internal/adapters/engine:
    config:
      dir: "./internal/mocks"
    interfaces:
      StateManagerInterface:
  github.com/hashicorp/raft:
    config:
      dir: "./internal/mocks"
    interfaces:
      FSM:
      LogStore:
      StableStore:
      SnapshotStore: