# Mockery configuration for Graft project
# This generates mocks for all interfaces in the ports package

with-expecter: true
keeptree: false
all: false
log-level: error
disable-version-string: true
mockname: "Mock{{.InterfaceName}}"
filename: "mock_{{.InterfaceName}}.go"
dir: "{{.InterfaceDir}}/mocks"
outpkg: "mocks"

packages:
  # Port interfaces - core abstractions
  github.com/eleven-am/graft/internal/ports:
    interfaces:
      DiscoveryPort:
      DiscoveryManager:
      StoragePort:
      QueuePort:
      TransportPort:
      NodePort:
      ResourceManagerPort:
      NodeRegistryPort:
      WorkflowEnginePort:
      SemaphorePort:
      RaftPort:

  # Engine package interfaces
  github.com/eleven-am/graft/internal/adapters/engine:
    interfaces:
      QueueCleaner:
      PendingEvaluator:
      EvaluationTrigger: