apiVersion: v1
kind: Service
metadata:
  name: graft-k8s-cluster
  namespace: default
  labels:
    app: graft-k8s
spec:
  selector:
    app: graft-k8s
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: transport
    port: 9090
    targetPort: 9090
  clusterIP: None  # Headless service for discovery

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graft-k8s-cluster
  namespace: default
  labels:
    app: graft-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: graft-k8s
  template:
    metadata:
      labels:
        app: graft-k8s
    spec:
      containers:
      - name: graft-node
        image: graft-k8s:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: transport
        env:
        - name: SERVICE_NAME
          value: "graft-k8s-cluster"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: SERVICE_PORT
          value: "8080"
        - name: TRANSPORT_PORT
          value: "9090"
        - name: DATA_DIR
          value: "/data"
        volumeMounts:
        - name: data-storage
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: data-storage
        emptyDir: {}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: graft-k8s
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: graft-k8s-discovery
  namespace: default
rules:
- apiGroups: [""]
  resources: ["endpoints", "services", "pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: graft-k8s-discovery
  namespace: default
subjects:
- kind: ServiceAccount
  name: graft-k8s
  namespace: default
roleRef:
  kind: Role
  name: graft-k8s-discovery
  apiGroup: rbac.authorization.k8s.io