node_id: "multi-node-example"
service_name: "multi-node-pipeline"
service_port: 8080

discovery:
  strategy: "static"
  
transport:
  listen_address: "127.0.0.1"
  listen_port: 9090

storage:
  data_dir: "./data/multi-node"
  
queue:
  data_dir: "./data/multi-node/queue"
  
resources:
  max_concurrent_total: 20
  default_per_type_limit: 5
  max_concurrent_per_type:
    data-processor: 8
    data-validator: 6
    data-store: 4
  
engine:
  max_concurrent_workflows: 10
  node_execution_timeout: "45s"
  
log_level: "info"