global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files: []

scrape_configs:
  - job_name: 'graft-cluster'
    static_configs:
      - targets: 
          - 'node-1:9091'
          - 'node-2:9091' 
          - 'node-3:9091'
    scrape_interval: 10s
    metrics_path: '/metrics'
    
  - job_name: 'graft-health'
    static_configs:
      - targets:
          - 'node-1:8080'
          - 'node-2:8080'
          - 'node-3:8080'
    scrape_interval: 5s
    metrics_path: '/health'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']