version: '3.8'

services:
  static-node-1:
    build: ../../../
    dockerfile: examples/discovery/static/Dockerfile
    container_name: static-node-1
    environment:
      - NODE_ID=static-node-1
      - SERVICE_PORT=8080
      - TRANSPORT_PORT=9090
      - PEERS=static-node-2:8080,static-node-3:8080
    ports:
      - "8081:8080"
      - "9091:9090"
    networks:
      - static-network
    volumes:
      - static1_data:/app/data

  static-node-2:
    build: ../../../
    dockerfile: examples/discovery/static/Dockerfile
    container_name: static-node-2
    environment:
      - NODE_ID=static-node-2
      - SERVICE_PORT=8080
      - TRANSPORT_PORT=9090
      - PEERS=static-node-1:8080,static-node-3:8080
    ports:
      - "8082:8080"
      - "9092:9090"
    networks:
      - static-network
    volumes:
      - static2_data:/app/data
    depends_on:
      - static-node-1

  static-node-3:
    build: ../../../
    dockerfile: examples/discovery/static/Dockerfile
    container_name: static-node-3
    environment:
      - NODE_ID=static-node-3
      - SERVICE_PORT=8080
      - TRANSPORT_PORT=9090
      - PEERS=static-node-1:8080,static-node-2:8080
    ports:
      - "8083:8080"
      - "9093:9090"
    networks:
      - static-network
    volumes:
      - static3_data:/app/data
    depends_on:
      - static-node-1

networks:
  static-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16

volumes:
  static1_data:
  static2_data:
  static3_data: