node_id: "node-1"
service_name: "basic-example"
service_port: 8080

discovery:
  strategy: "static"
  
transport:
  listen_address: "127.0.0.1"
  listen_port: 9090

storage:
  data_dir: "./data/basic"
  
queue:
  data_dir: "./data/basic/queue"
  
resources:
  max_concurrent_total: 10
  default_per_type_limit: 5
  
engine:
  max_concurrent_workflows: 5
  node_execution_timeout: "30s"
  
log_level: "info"